import { expect, test } from "@playwright/test";

test.describe("builder dashboard flow", () => {
  test("creates a project and generates a canonical plan from the UI", async ({ page }) => {
    await page.goto("/builder");

    await expect(page.getByText("builder mode")).toBeVisible();

    const projectName = `E2E Builder ${Date.now()}`;

    await page.getByTestId("builder-create-project-name").fill(projectName);
    await page.getByTestId("builder-create-project-button").click();

    await expect(page.getByText(`Created project ${projectName}.`)).toBeVisible();
    await expect(page.getByText(projectName).first()).toBeVisible();
    await page.waitForLoadState("networkidle");

    await page.getByTestId("builder-brief-title").fill("E2E Builder Smoke");
    await page.getByTestId("builder-brief-summary").fill("Create a minimal builder smoke plan and stage the first canonical task.");
    await page.getByTestId("builder-brief-notes").fill("Generated by Playwright builder smoke coverage.");

    const planResponsePromise = page.waitForResponse((response) => response.url().includes("/api/builder/projects/")
      && response.url().endsWith("/plan")
      && response.request().method() === "POST");
    await page.getByTestId("builder-save-plan-button").click();
    const planResponse = await planResponsePromise;
    expect(planResponse.ok()).toBe(true);

    await expect(page.getByText("Updated the project brief and regenerated the canonical Builder plan.")).toBeVisible();
    await expect(page.getByTestId("builder-selected-project-lifecycle")).toHaveText("planned");
    await expect(page.getByText("current task", { exact: true })).toBeVisible();
    await expect(page.getByText("next recommended step", { exact: true })).toBeVisible();

    await expect(page.getByText("No canonical Builder plan has been generated yet.")).not.toBeVisible();
  });
});