import { expect, test } from "@playwright/test";

test.describe("builder dashboard flow", () => {
  const createdProjectNames: string[] = [];

  test.afterEach(async ({ page }) => {
    // Clean up any projects created during the test to avoid stale workspace folders
    for (const name of createdProjectNames) {
      try {
        await page.goto("/builder");
        const button = page.getByRole("button", { name: new RegExp(name) });
        if (await button.isVisible({ timeout: 2000 })) {
          await button.click();
          await page.getByTestId("builder-delete-project-button").click();
          await page.getByTestId("builder-delete-confirm").click();
        }
      } catch {
        // Best-effort cleanup
      }
    }
    createdProjectNames.length = 0;
  });

  test("creates a project and generates a canonical plan from the UI", async ({ page }, testInfo) => {
    await page.goto("/builder");

    await expect(page.getByText("builder mode")).toBeVisible();

    const projectName = `E2E Builder ${Date.now()}-${testInfo.parallelIndex}-${testInfo.repeatEachIndex}`;
    createdProjectNames.push(projectName);

    await page.getByTestId("builder-create-project-name").fill(projectName);
    await page.getByTestId("builder-create-project-button").click();

    await expect(page.getByRole("button", { name: new RegExp(projectName) })).toBeVisible();
    await page.waitForLoadState("networkidle");

    const titleInput = page.getByTestId("builder-brief-title");
    const summaryInput = page.getByTestId("builder-brief-summary");
    const notesInput = page.getByTestId("builder-brief-notes");
    await expect(page.getByTestId("builder-selected-project-lifecycle")).toHaveText("draft");
    await expect(page.getByText(projectName).first()).toBeVisible();
    await expect(titleInput).toBeVisible();
    await expect(summaryInput).toBeVisible();

    await titleInput.fill("E2E Builder Smoke");
    await summaryInput.fill("Create a minimal builder smoke plan and stage the first canonical task.");
    await notesInput.fill("Generated by Playwright builder smoke coverage.");
    await expect(titleInput).toHaveValue("E2E Builder Smoke");
    await expect(summaryInput).toHaveValue("Create a minimal builder smoke plan and stage the first canonical task.");
    await expect(notesInput).toHaveValue("Generated by Playwright builder smoke coverage.");

    const planResponsePromise = page.waitForResponse((response) => response.url().includes("/api/builder/projects/")
      && response.url().endsWith("/plan")
      && response.request().method() === "POST");
    await page.getByTestId("builder-save-plan-button").click();
    const planResponse = await planResponsePromise;
    expect(planResponse.ok()).toBe(true);

    await expect(page.getByText("Updated the project brief and regenerated the canonical Builder plan.")).toBeVisible();
    await expect(page.getByTestId("builder-selected-project-lifecycle")).toHaveText("planned");
    await expect(page.getByText("current task", { exact: true })).toBeVisible();
    await expect(page.getByText("next recommended step", { exact: true })).toBeVisible();

    await expect(page.getByText("No canonical Builder plan has been generated yet.")).not.toBeVisible();
  });

  test("records and renders governance policy decisions in history", async ({ page }, testInfo) => {
    await page.goto("/builder");

    await expect(page.getByText("builder mode")).toBeVisible();

    const projectName = `E2E Governance ${Date.now()}-${testInfo.parallelIndex}-${testInfo.repeatEachIndex}`;
    createdProjectNames.push(projectName);
    const reason = `Playwright governance policy reconcile ${Date.now()}`;

    await page.getByTestId("builder-create-project-name").fill(projectName);
    await page.getByTestId("builder-create-project-button").click();

    await expect(page.getByRole("button", { name: new RegExp(projectName) })).toBeVisible();
    await page.waitForLoadState("networkidle");
    await expect(page.getByTestId("builder-governance-panel")).toBeVisible();

    await page.getByTestId("builder-governance-reason").fill(reason);
    await page.getByTestId("builder-governance-confirmed").check();

    const responsePromise = page.waitForResponse((response) => response.url().includes("/api/builder/projects/")
      && response.url().endsWith("/commands")
      && response.request().method() === "POST");
    await page.getByTestId("builder-governance-reconcile-policy").click();
    const response = await responsePromise;
    expect(response.ok()).toBe(true);

    await expect(page.getByTestId("builder-governance-toast")).toContainText("Governance action recorded");
    await expect(page.getByTestId("builder-governance-toast")).toContainText("Reconciled the Builder MCP policy baseline from the dashboard.");
    await expect(page.getByTestId("builder-governance-history")).toContainText(reason);
    await expect(page.getByTestId("builder-governance-history")).toContainText("source dashboard");
  });
});