ALTER TYPE "BuilderRunKind" ADD VALUE IF NOT EXISTS 'CONTAINER_EXEC';
ALTER TYPE "BuilderRunKind" ADD VALUE IF NOT EXISTS 'CONTAINER_TEST';
ALTER TYPE "BuilderRunKind" ADD VALUE IF NOT EXISTS 'CONTAINER_START';
ALTER TYPE "BuilderRunKind" ADD VALUE IF NOT EXISTS 'CONTAINER_STOP';
ALTER TYPE "BuilderRunKind" ADD VALUE IF NOT EXISTS 'CONTAINER_RESTART';
